# Generated by Django 5.2.17 on 2026-08-14 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_product_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('position', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the filter panel.')),
                ('categories', models.ManyToManyField(blank=True, help_text='Categories whose filter panel shows this attribute.', related_name='attributes', to='ecommerce.category')),
            ],
            options={
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=90)),
                ('position', models.PositiveIntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='ecommerce.attribute')),
            ],
            options={
                'ordering': ('position', 'name'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, related_name='products', to='ecommerce.attributevalue'),
        ),
        migrations.AddConstraint(
            model_name='attributevalue',
            constraint=models.UniqueConstraint(fields=('attribute', 'slug'), name='unique_value_slug_per_attribute'),
        ),
    ]
