# Generated by Django 5.2.17 on 2026-08-14 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_attribute_attributevalue_product_attribute_values_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_ratings_given', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_ratings_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
                'constraints': [models.UniqueConstraint(fields=('seller', 'customer'), name='unique_customer_rating_per_seller'), models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 5)), name='seller_rating_score_between_1_and_5'), models.CheckConstraint(condition=models.Q(('seller', models.F('customer')), _negated=True), name='seller_cannot_rate_self')],
            },
        ),
    ]
