# Generated by Django 5.2.17 on 2026-08-17 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=64, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text="Leave empty to use the product's price.", max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, help_text='Shown instead of the product description when set.')),
                ('image', models.ImageField(blank=True, upload_to='variants/%Y/%m/')),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='uniq_cart_product',
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='swatch_color',
            field=models.CharField(blank=True, help_text='Hex colour like #1D4ED8, for values shown as a swatch.', max_length=7),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='option_values',
            field=models.ManyToManyField(blank=True, related_name='variants', to='ecommerce.attributevalue'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='ecommerce.product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='ecommerce.productvariant'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'variant'), name='uniq_cart_product_variant'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('cart', 'product'), name='uniq_cart_product_without_variant'),
        ),
    ]
