# Generated by Django 5.2.17 on 2026-08-18 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_productvariant_remove_cartitem_uniq_cart_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='gallery/%Y/%m/')),
                ('image_url', models.URLField(blank=True)),
                ('alt', models.CharField(blank=True, help_text='Describes the photo for screen readers.', max_length=140)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='ecommerce.product')),
                ('variant', models.ForeignKey(blank=True, help_text='Leave empty to show this photo for every variant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='ecommerce.productvariant')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
    ]
