# Generated by Django 5.2.17 on 2026-08-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='store_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
