from rest_framework import serializers

from ..models import Attribute, AttributeValue, Category, Product


class SellerRatingInputSerializer(serializers.Serializer):
    score = serializers.IntegerField(min_value=1, max_value=5)


class CategorySerializer(serializers.ModelSerializer):
    class Meta:
        model = Category
        fields = ("id", "name", "slug")


class AttributeValueSerializer(serializers.ModelSerializer):
    class Meta:
        model = AttributeValue
        fields = ("id", "name", "slug")


class AttributeSerializer(serializers.ModelSerializer):
    values = AttributeValueSerializer(many=True, read_only=True)
    # Category ids so the seller form can show only the relevant attributes
    # once a category is picked.
    categories = serializers.PrimaryKeyRelatedField(many=True, read_only=True)

    class Meta:
        model = Attribute
        fields = ("id", "name", "slug", "categories", "values")


class SellerProductSerializer(serializers.ModelSerializer):
    """Read/write serializer for the seller panel."""

    category_name = serializers.CharField(source="category.name", read_only=True)
    image_display = serializers.SerializerMethodField()
    attribute_values = serializers.PrimaryKeyRelatedField(
        many=True,
        required=False,
        queryset=AttributeValue.objects.all(),
    )

    class Meta:
        model = Product
        fields = (
            "id",
            "name",
            "slug",
            "description",
            "price",
            "stock",
            "category",
            "category_name",
            "attribute_values",
            "image",
            "image_url",
            "image_display",
            "is_active",
            "created_at",
        )
        # slug is generated by Product.save(); seller is set from the request
        # in the view and is intentionally not a writable field.
        read_only_fields = ("id", "slug", "created_at")

    def get_image_display(self, obj):
        image = obj.display_image
        if not image:
            return ""
        request = self.context.get("request")
        if request is not None and image.startswith("/"):
            return request.build_absolute_uri(image)
        return image

    def validate_price(self, value):
        if value <= 0:
            raise serializers.ValidationError("Price must be greater than zero.")
        return value

    def validate(self, attrs):
        # Reject values that do not belong to the chosen category, so a
        # graphics card cannot be tagged with "Colour: Black".
        category = attrs.get("category") or getattr(self.instance, "category", None)
        values = attrs.get("attribute_values")

        if category is not None and values:
            allowed = set(
                Attribute.objects.filter(categories=category).values_list(
                    "id", flat=True
                )
            )
            stray = [
                value.name for value in values if value.attribute_id not in allowed
            ]
            if stray:
                raise serializers.ValidationError(
                    {
                        "attribute_values": [
                            f"These do not apply to {category.name}: "
                            + ", ".join(stray)
                        ]
                    }
                )

        return attrs


class ProductSerializer(serializers.ModelSerializer):
    # Expose the category by name and slug so the frontend does not need
    # a second request just to show which category a product belongs to.
    category = serializers.CharField(source="category.name", read_only=True)
    category_slug = serializers.CharField(source="category.slug", read_only=True)

    # Keeps a single image field in the API whether the picture was uploaded
    # or pasted as a link, so the frontend never has to choose between two.
    image_url = serializers.SerializerMethodField()
    seller = serializers.SerializerMethodField()

    def get_image_url(self, obj):
        image = obj.display_image
        if not image:
            return ""

        # Uploaded files come back as a relative path; make it absolute so
        # the Next.js server and the Flutter app can both load it.
        request = self.context.get("request")
        if request is not None and image.startswith("/"):
            return request.build_absolute_uri(image)
        return image

    def get_seller(self, obj):
        seller = obj.seller
        if seller is None:
            return None

        ratings = list(seller.seller_ratings_received.all())
        rating_count = len(ratings)
        average = (
            round(sum(rating.score for rating in ratings) / rating_count, 1)
            if rating_count
            else None
        )
        return {
            "id": seller.id,
            "name": seller.seller_display_name,
            "is_verified": seller.is_verified_seller,
            "rating": average,
            "rating_count": rating_count,
        }

    class Meta:
        model = Product
        fields = (
            "id",
            "name",
            "slug",
            "description",
            "price",
            "stock",
            "in_stock",
            "category",
            "category_slug",
            "image_url",
            "seller",
        )
