import re

from rest_framework import serializers

from ..models import (
    Attribute,
    AttributeValue,
    Cart,
    CartItem,
    Category,
    Product,
    ProductImage,
    ProductVariant,
)


class SellerRatingInputSerializer(serializers.Serializer):
    score = serializers.IntegerField(min_value=1, max_value=5)


class CategorySerializer(serializers.ModelSerializer):
    class Meta:
        model = Category
        fields = ("id", "name", "slug")


class AttributeValueSerializer(serializers.ModelSerializer):
    class Meta:
        model = AttributeValue
        # swatch_color travels with the value so both the shopper's picker
        # and the seller's grid can draw a colour as a dot.
        fields = ("id", "name", "slug", "swatch_color")


class AttributeSerializer(serializers.ModelSerializer):
    values = AttributeValueSerializer(many=True, read_only=True)
    # Category ids so the seller form can show only the relevant attributes
    # once a category is picked.
    categories = serializers.PrimaryKeyRelatedField(many=True, read_only=True)

    class Meta:
        model = Attribute
        fields = ("id", "name", "slug", "categories", "values")


class SellerProductSerializer(serializers.ModelSerializer):
    """Read/write serializer for the seller panel."""

    category_name = serializers.CharField(source="category.name", read_only=True)
    image_display = serializers.SerializerMethodField()
    attribute_values = serializers.PrimaryKeyRelatedField(
        many=True,
        required=False,
        queryset=AttributeValue.objects.all(),
    )

    class Meta:
        model = Product
        fields = (
            "id",
            "name",
            "slug",
            "description",
            "price",
            "stock",
            "category",
            "category_name",
            "attribute_values",
            "image",
            "image_url",
            "image_display",
            "is_active",
            "created_at",
        )
        # slug is generated by Product.save(); seller is set from the request
        # in the view and is intentionally not a writable field.
        read_only_fields = ("id", "slug", "created_at")

    def get_image_display(self, obj):
        image = obj.display_image
        if not image:
            return ""
        request = self.context.get("request")
        if request is not None and image.startswith("/"):
            return request.build_absolute_uri(image)
        return image

    def validate_price(self, value):
        if value <= 0:
            raise serializers.ValidationError("Price must be greater than zero.")
        return value

    def validate(self, attrs):
        # Reject values that do not belong to the chosen category, so a
        # graphics card cannot be tagged with "Colour: Black".
        category = attrs.get("category") or getattr(self.instance, "category", None)
        values = attrs.get("attribute_values")

        if category is not None and values:
            allowed = set(
                Attribute.objects.filter(categories=category).values_list(
                    "id", flat=True
                )
            )
            stray = [
                value.name for value in values if value.attribute_id not in allowed
            ]
            if stray:
                raise serializers.ValidationError(
                    {
                        "attribute_values": [
                            f"These do not apply to {category.name}: "
                            + ", ".join(stray)
                        ]
                    }
                )

        return attrs


class ProductImageSerializer(serializers.ModelSerializer):
    """
    One photo in the gallery strip.

    `variant` is null for photos that belong to the product as a whole;
    the client keeps those on screen whichever variant is chosen and shows
    the variant-specific ones alongside.
    """

    url = serializers.SerializerMethodField()

    class Meta:
        model = ProductImage
        fields = ("id", "url", "alt", "variant", "position")
        read_only_fields = fields

    def get_url(self, obj):
        image = obj.display_image
        if not image:
            return ""
        request = self.context.get("request")
        if request is not None and image.startswith("/"):
            return request.build_absolute_uri(image)
        return image


#: How many extra photos a product may carry, beyond its cover. Enough to
#: show a product from every side without turning the strip into a scroll.
MAX_GALLERY_PHOTOS = 6


class SellerProductImageSerializer(serializers.ModelSerializer):
    """Write serializer for the seller panel's gallery."""

    url = serializers.SerializerMethodField()

    class Meta:
        model = ProductImage
        fields = (
            "id",
            "url",
            "image",
            "image_url",
            "alt",
            "variant",
            "position",
        )
        read_only_fields = ("id", "url")
        extra_kwargs = {"image": {"write_only": True}}

    def get_url(self, obj):
        image = obj.display_image
        if not image:
            return ""
        request = self.context.get("request")
        if request is not None and image.startswith("/"):
            return request.build_absolute_uri(image)
        return image

    def validate_variant(self, value):
        # A photo can only be pinned to a variant of the same product.
        if value is not None and value.product_id != self.context["product"].pk:
            raise serializers.ValidationError(
                "That variant belongs to another product."
            )
        return value

    def validate(self, attrs):
        image = attrs.get("image", getattr(self.instance, "image", None))
        link = attrs.get("image_url", getattr(self.instance, "image_url", ""))
        if not image and not link:
            raise serializers.ValidationError(
                {"image_url": ["Upload a file or paste a link."]}
            )

        # Only on create: editing the sixth photo must stay possible.
        if self.instance is None:
            existing = self.context["product"].gallery.count()
            if existing >= MAX_GALLERY_PHOTOS:
                raise serializers.ValidationError(
                    {
                        "image_url": [
                            f"A product can have {MAX_GALLERY_PHOTOS} extra "
                            "photos. Remove one to add another."
                        ]
                    }
                )

        return attrs

    def update(self, instance, validated_data):
        """
        Moving a photo pushes the others aside.

        Writing the new position alone left two rows claiming the same
        index, and the strip then fell back to insertion order — so "move
        to the front" quietly did nothing.
        """
        moved_to = validated_data.pop("position", None)
        instance = super().update(instance, validated_data)

        if moved_to is None:
            return instance

        siblings = [
            photo
            for photo in instance.product.gallery.order_by("position", "id")
            if photo.pk != instance.pk
        ]
        siblings.insert(min(max(int(moved_to), 0), len(siblings)), instance)

        for index, photo in enumerate(siblings):
            if photo.position != index:
                photo.position = index
                photo.save(update_fields=["position"])

        instance.refresh_from_db()
        return instance


class ProductVariantSerializer(serializers.ModelSerializer):
    """
    One buyable combination.

    `option_value_ids` is what the client matches its selection against:
    pick one value per group, find the variant whose set equals the picks.
    """

    option_value_ids = serializers.SerializerMethodField()
    option_label = serializers.CharField(read_only=True)
    price = serializers.DecimalField(
        source="effective_price", max_digits=10, decimal_places=2, read_only=True
    )
    description = serializers.CharField(
        source="effective_description", read_only=True
    )
    image_url = serializers.SerializerMethodField()
    in_stock = serializers.BooleanField(read_only=True)

    class Meta:
        model = ProductVariant
        fields = (
            "id",
            "sku",
            "option_value_ids",
            "option_label",
            "price",
            "stock",
            "in_stock",
            "description",
            "image_url",
        )
        read_only_fields = fields

    def get_option_value_ids(self, obj):
        return sorted(value.id for value in obj.option_values.all())

    def get_image_url(self, obj):
        image = obj.display_image
        if not image:
            return ""
        request = self.context.get("request")
        if request is not None and image.startswith("/"):
            return request.build_absolute_uri(image)
        return image


class ProductSerializer(serializers.ModelSerializer):
    # Expose the category by name and slug so the frontend does not need
    # a second request just to show which category a product belongs to.
    category = serializers.CharField(source="category.name", read_only=True)
    category_slug = serializers.CharField(source="category.slug", read_only=True)

    # Keeps a single image field in the API whether the picture was uploaded
    # or pasted as a link, so the frontend never has to choose between two.
    image_url = serializers.SerializerMethodField()
    seller = serializers.SerializerMethodField()

    has_variants = serializers.BooleanField(read_only=True)
    images = ProductImageSerializer(source="gallery", many=True, read_only=True)
    # The product's own stock column stays 0 once variants carry it, so the
    # badge needs the total rather than the column.
    total_stock = serializers.IntegerField(read_only=True)
    variants = ProductVariantSerializer(
        source="active_variants", many=True, read_only=True
    )
    option_groups = serializers.SerializerMethodField()
    price_from = serializers.SerializerMethodField()
    price_to = serializers.SerializerMethodField()

    def get_option_groups(self, obj):
        """
        The pickers to draw, in attribute order.

        Built from the values the variants actually use, so an option with
        no variant behind it never appears as a dead choice.
        """
        groups = {}
        for variant in obj.active_variants:
            for value in variant.option_values.all():
                attribute = value.attribute
                group = groups.setdefault(
                    attribute.id,
                    {
                        "name": attribute.name,
                        "slug": attribute.slug,
                        "position": attribute.position,
                        "values": {},
                    },
                )
                group["values"][value.id] = {
                    "id": value.id,
                    "name": value.name,
                    "slug": value.slug,
                    "swatch_color": value.swatch_color,
                    "position": value.position,
                }

        ordered = sorted(groups.values(), key=lambda item: item["position"])
        for group in ordered:
            group["values"] = sorted(
                group["values"].values(),
                key=lambda item: (item["position"], item["name"]),
            )
            group.pop("position")
        return ordered

    def get_price_from(self, obj):
        return str(obj.price_range[0])

    def get_price_to(self, obj):
        return str(obj.price_range[1])

    def get_image_url(self, obj):
        image = obj.display_image
        if not image:
            return ""

        # Uploaded files come back as a relative path; make it absolute so
        # the Next.js server and the Flutter app can both load it.
        request = self.context.get("request")
        if request is not None and image.startswith("/"):
            return request.build_absolute_uri(image)
        return image

    def get_seller(self, obj):
        seller = obj.seller
        if seller is None:
            return None

        ratings = list(seller.seller_ratings_received.all())
        rating_count = len(ratings)
        average = (
            round(sum(rating.score for rating in ratings) / rating_count, 1)
            if rating_count
            else None
        )
        return {
            "id": seller.id,
            "name": seller.seller_display_name,
            "is_verified": seller.is_verified_seller,
            "rating": average,
            "rating_count": rating_count,
        }

    class Meta:
        model = Product
        fields = (
            "id",
            "name",
            "slug",
            "description",
            "price",
            "stock",
            "in_stock",
            "category",
            "category_slug",
            "image_url",
            "seller",
            "has_variants",
            "total_stock",
            "images",
            "variants",
            "option_groups",
            "price_from",
            "price_to",
        )


class CartItemSerializer(serializers.ModelSerializer):
    """
    One line in the cart.

    Prices are read from the product on every request, so a price change in
    the shop shows up in the cart immediately. Stock is reported alongside
    so the client can show a warning without a second lookup.
    """

    product_id = serializers.IntegerField(source="product.id", read_only=True)
    variant_id = serializers.IntegerField(read_only=True)
    name = serializers.CharField(source="product.name", read_only=True)
    slug = serializers.CharField(source="product.slug", read_only=True)
    # "White / US 7", empty for products sold without options.
    option_label = serializers.SerializerMethodField()
    image_url = serializers.SerializerMethodField()
    unit_price = serializers.DecimalField(
        max_digits=10, decimal_places=2, read_only=True
    )
    line_total = serializers.DecimalField(
        max_digits=12, decimal_places=2, read_only=True
    )
    available_stock = serializers.IntegerField(read_only=True)
    has_stock_issue = serializers.BooleanField(read_only=True)

    class Meta:
        model = CartItem
        fields = (
            "id",
            "product_id",
            "variant_id",
            "name",
            "slug",
            "option_label",
            "image_url",
            "quantity",
            "unit_price",
            "line_total",
            "available_stock",
            "has_stock_issue",
        )
        read_only_fields = fields

    def get_option_label(self, obj):
        return obj.variant.option_label if obj.variant else ""

    def get_image_url(self, obj):
        image = obj.image
        if not image:
            return ""
        request = self.context.get("request")
        if request is not None and image.startswith("/"):
            return request.build_absolute_uri(image)
        return image


class CartSerializer(serializers.ModelSerializer):
    items = CartItemSerializer(many=True, read_only=True)
    item_count = serializers.IntegerField(read_only=True)
    subtotal = serializers.DecimalField(
        max_digits=12, decimal_places=2, read_only=True
    )
    has_stock_issues = serializers.SerializerMethodField()

    class Meta:
        model = Cart
        fields = ("id", "items", "item_count", "subtotal", "has_stock_issues")
        read_only_fields = fields

    def get_has_stock_issues(self, obj):
        # Checkout will need to block on this, so the flag is computed once
        # here rather than re-derived by each client.
        return any(item.has_stock_issue for item in obj.items.all())


class AddToCartSerializer(serializers.Serializer):
    product_id = serializers.IntegerField()
    # Required for products that have options; the service rejects the
    # request when it is missing.
    variant_id = serializers.IntegerField(required=False, allow_null=True)
    quantity = serializers.IntegerField(required=False, default=1, min_value=1)


class UpdateCartItemSerializer(serializers.Serializer):
    quantity = serializers.IntegerField(min_value=1)


class SellerVariantSerializer(serializers.ModelSerializer):
    """
    Read/write serializer for the seller panel's variant grid.

    The product is taken from the URL, never the body, so a seller cannot
    attach a variant to somebody else's listing.
    """

    option_values = serializers.PrimaryKeyRelatedField(
        many=True,
        queryset=AttributeValue.objects.select_related("attribute"),
    )
    option_label = serializers.CharField(read_only=True)
    image_display = serializers.SerializerMethodField()

    class Meta:
        model = ProductVariant
        fields = (
            "id",
            "sku",
            "option_values",
            "option_label",
            "price",
            "stock",
            "description",
            "image",
            "image_url",
            "image_display",
            "is_active",
            "position",
        )
        read_only_fields = ("id", "sku")

    def get_image_display(self, obj):
        image = obj.display_image
        if not image:
            return ""
        request = self.context.get("request")
        if request is not None and image.startswith("/"):
            return request.build_absolute_uri(image)
        return image

    def validate_price(self, value):
        # Null is the "same as the product" case and stays allowed.
        if value is not None and value <= 0:
            raise serializers.ValidationError("Price must be greater than zero.")
        return value

    def validate_option_values(self, values):
        if not values:
            raise serializers.ValidationError("Pick at least one option.")

        # A variant is one point in the grid, so two values of the same
        # attribute cannot both apply: nothing is White and Black at once.
        seen = {}
        for value in values:
            if value.attribute_id in seen:
                raise serializers.ValidationError(
                    f"Pick only one {value.attribute.name}: "
                    f"{seen[value.attribute_id]} and {value.name} clash."
                )
            seen[value.attribute_id] = value.name

        product = self.context["product"]
        allowed = set(
            Attribute.objects.filter(categories=product.category).values_list(
                "id", flat=True
            )
        )
        stray = [value.name for value in values if value.attribute_id not in allowed]
        if stray:
            raise serializers.ValidationError(
                f"These do not apply to {product.category.name}: "
                + ", ".join(stray)
            )

        return values

    def validate(self, attrs):
        values = attrs.get("option_values")
        if values is None:
            return attrs

        product = self.context["product"]
        combination = {value.pk for value in values}

        # Two rows with the same options would be two prices for one thing.
        siblings = product.variants.prefetch_related("option_values")
        if self.instance is not None:
            siblings = siblings.exclude(pk=self.instance.pk)

        for sibling in siblings:
            if {value.pk for value in sibling.option_values.all()} == combination:
                raise serializers.ValidationError(
                    {"option_values": [f"{sibling.option_label} already exists."]}
                )

        return attrs


class VariantGenerateSerializer(serializers.Serializer):
    """
    Input for "build every combination": a flat list of chosen values.

    They arrive flat because that is what a grid of checkboxes produces;
    the view groups them by attribute before taking the product.
    """

    value_ids = serializers.PrimaryKeyRelatedField(
        many=True,
        queryset=AttributeValue.objects.select_related("attribute"),
    )


class SellerOptionSerializer(serializers.Serializer):
    """
    Input for the "+" buttons in the seller's variant picker.

    Either extends an existing group (`attribute_id`) or starts a new one
    (`attribute_name`), and always adds one value. Sellers cannot reach the
    Django admin, so this is the only way for them to say "this shoe also
    comes in 45".
    """

    attribute_id = serializers.IntegerField(required=False)
    attribute_name = serializers.CharField(
        required=False, allow_blank=True, max_length=80
    )
    name = serializers.CharField(max_length=80)
    swatch_color = serializers.CharField(
        required=False, allow_blank=True, max_length=7
    )

    def validate_name(self, value):
        value = value.strip()
        if not value:
            raise serializers.ValidationError("Type a name for the option.")
        return value

    def validate_swatch_color(self, value):
        value = value.strip()
        if not value:
            return ""
        if not re.fullmatch(r"#[0-9A-Fa-f]{6}", value):
            raise serializers.ValidationError(
                "Use a hex colour like #1D4ED8."
            )
        return value.upper()

    def validate(self, attrs):
        if not attrs.get("attribute_id") and not attrs.get("attribute_name", "").strip():
            raise serializers.ValidationError(
                {"attribute_name": ["Say which option group this belongs to."]}
            )
        return attrs
